// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97Y4doDoq7VhSFF2DJY4F4Hew8mKnj9M',
    appId: '1:595635452401:web:19268e543325cc23502c50',
    messagingSenderId: '595635452401',
    projectId: 'cargo-70ac0',
    authDomain: 'cargo-70ac0.firebaseapp.com',
    storageBucket: 'cargo-70ac0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGquYOmcJNE6AljHJtjQvaVbZogveczn0',
    appId: '1:595635452401:android:abedf2a4590ceab4502c50',
    messagingSenderId: '595635452401',
    projectId: 'cargo-70ac0',
    storageBucket: 'cargo-70ac0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXmAu-dMIPUQflg-B1_rmD4FzeGi5JlEE',
    appId: '1:595635452401:ios:bd11516b852af92b502c50',
    messagingSenderId: '595635452401',
    projectId: 'cargo-70ac0',
    storageBucket: 'cargo-70ac0.firebasestorage.app',
    iosBundleId: 'com.example.plataformasMoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXmAu-dMIPUQflg-B1_rmD4FzeGi5JlEE',
    appId: '1:595635452401:ios:bd11516b852af92b502c50',
    messagingSenderId: '595635452401',
    projectId: 'cargo-70ac0',
    storageBucket: 'cargo-70ac0.firebasestorage.app',
    iosBundleId: 'com.example.plataformasMoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB97Y4doDoq7VhSFF2DJY4F4Hew8mKnj9M',
    appId: '1:595635452401:web:34b701dfe5307a76502c50',
    messagingSenderId: '595635452401',
    projectId: 'cargo-70ac0',
    authDomain: 'cargo-70ac0.firebaseapp.com',
    storageBucket: 'cargo-70ac0.firebasestorage.app',
  );
}
